#!/bin/bash
# run_schlacount.sh
# This script runs scHLAcount to generate cell-by-allele molecule counts
# based on personalized HLA references.

source ../../project_config.txt

# Input: HLA VCF or allele list generated by generate_hla_vcf.sh
# scHLAcount requires a BAM file and a list of HLA alleles.

OUTPUT_DIR=$PROJECT_PATH/pipeline/RNA.FB.VDJ/scHLAcount_outputs
HLA_ALLELE_FILE=$PROJECT_PATH/pipeline/RNA.FB.VDJ/hla_alleles.csv

if [ ! -f $HLA_ALLELE_FILE ]; then
  echo "ERROR: hla_alleles.csv not found. Please provide known alleles."
  exit 1
fi

mkdir -p $OUTPUT_DIR

SAMPLES_ARRAY=($(ls -d $PROJECT_PATH/*/pipeline/RNA.FB.VDJ/*/))

for sample_path in "${SAMPLES_ARRAY[@]}"; do
  sample_name=$(basename $sample_path)
  if [[ $sample_name != reports ]] && [[ ! $sample_name =~ _aggr$ ]] && [[ ! $sample_name =~ _demuxing$ ]]; then
    
    BAM=${sample_path}outs/per_sample_outs/$sample_name/count/sample_alignments.bam
    
    if [ -f $BAM ]; then
      echo "Running scHLAcount for sample $sample_name..."
      # Example usage (assuming scHLAcount is in PATH)
      # scHLAcount -b $BAM -a $HLA_ALLELE_FILE -o $OUTPUT_DIR/$sample_name
      # Note: scHLAcount usually needs a specific format for alleles.
      echo "scHLAcount -b $BAM -a $HLA_ALLELE_FILE -o $OUTPUT_DIR/$sample_name"
    fi
  fi
done
