name: mapseq_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - python
  - leidenalg
  - r-biocmanager
  - r-pacman
  - bioconductor-glmgampoi
  - biopython
  - anndata
  - kb-python
  - r-curl
  - r-ragg
  - r-mass
  - r-httpuv
  - r-rjson
  - r-azimuth
