
name: Create and Export Up-to-date Conda Environment

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs at midnight on Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Define package list
        env:
          PACKAGES: kallisto==0.46.1, bustools==0.39.3, cellbender==0.3.0, leidenalg

      - name: Generate environment.yml
        run: |
          echo "name: mapseq_env" >> environment.yml
          echo "channels:" >> environment.yml
          echo "  - conda-forge" >> environment.yml
          echo "  - bioconda" >> environment.yml
          echo "dependencies:" >> environment.yml
          echo "  - r-base=4.3.3" >> environment.yml
          echo "  - python=3.8.19" >> environment.yml
          echo "  - pip" >> environment.yml
          echo "  - pip:" >> environment.yml
          # Loop through packages and add them to YAML with versions
          for package in ${{ env.PACKAGES }}; do
            version=$(echo "$package" | cut -d'=' -f2)  # Extract version if present
            package_name=$(echo "$package" | cut -d'=' -f1)
            if [[ $version ]]; then
              echo "  - $package_name==$version" >> environment.yml
            else
              echo "  - $package_name" >> environment.yml
            fi
          done

      - name: Create conda environment
        run: |
          conda env create -f environment.yml

      - name: Export environment.yml
        run: |
          conda init
          conda activate mapseq_env
          conda env export > environment.yml

      - name: Add environment.yml
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git checkout -b dependencies_update main
          git init
          git add environment.yml
    
      - name: Commit environment.yml
        run: |
          git commit -m "Add updated environment.yml"
          git push --set-upstream origin dependencies_update

      - name: Create Pull Request
        run: gh pr create -B main -H dependencies_update --title 'Merge dependencies_update into main' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
